### ISSUE TITLE
segmentation fault (core dumped) on python ./export_trt.py

### ISSUE THREAD

**Issue by chrisbward** [yuvraj108c/ComfyUI-Dwpose-Tensorrt#4]
Hi,

I've downloaded the models and made an attempt to convert to tensorrt, but seem to be hitting this issue at 50% progress of building the engine.

Ubuntu 20.04, Python 3.10.13 (venv)
I've downgraded the tensorrt pip package to 10.2.0 from 10.3.0 (same result)

```
➜  ~ nvidia-smi
Fri Aug 23 07:14:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     Off | 00000000:01:00.0  On |                    0 |
| 35%   63C    P3              75W / 450W |   1957MiB / 23028MiB |     36%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

```

**Comment by chrisbward** [comment]
okay, after many hours spent, I finally managed to convert the model using nvidia's `trtexec` tool - also ran;
```
python -m pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==10.2.0.post1 --no-cache-dir
```

might help someone, not really sure which command 100s fixed it in the end

**Comment by Latentnaut** [comment]
@chrisbward 

Could you please help me to build the TensorRT? My skills are really not enough to understand what I have to do. I'm in Windows, Comfyui portable version.

The repository says: Build tensorrt engines for both of these models by running: python export_trt.py

For someone that has never done this, what exactly I have to proceed? Please for dummys.

On the other hand, when I run the requirements for Estimator, I got this error:

`C:\AI\ComfyUI_windows_portable_sand\ComfyUI\custom_nodes\ComfyUI-ultimate-openpose-estimator>..\..\..\python_embeded\python.exe -m pip install -r requirements.txt
Collecting tensorrt (from -r requirements.txt (line 1))
  Using cached tensorrt-10.9.0.34.tar.gz (40 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running dist_info
      creating C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info
      writing C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\PKG-INFO
      writing dependency_links to C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\dependency_links.txt
      writing requirements to C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\requires.txt
      writing top-level names to C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\top_level.txt
      writing manifest file 'C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\SOURCES.txt'
      adding license file 'LICENSE.txt'
      writing manifest file 'C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt.egg-info\SOURCES.txt'
      creating 'C:\Users\info\AppData\Local\Temp\pip-modern-metadata-iidt_rj4\tensorrt-10.9.0.34.dist-info'
      error: invalid command 'bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by yuvraj108c** [comment]
try installing wheel
..\..\..\python_embeded\python.exe -m pip install wheel

**Comment by Latentnaut** [comment]
Hi @yuvraj108c , thank you for your support.

After installing wheel, I run again and get this:

```
C:\AI\ComfyUI_windows_portable_sand\ComfyUI\custom_nodes\ComfyUI-ultimate-openpose-estimator>..\..\..\python_embeded\python.exe -m pip install -r requirements.txt
Collecting tensorrt (from -r requirements.txt (line 1))
  Using cached tensorrt-10.9.0.34.tar.gz (40 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: polygraphy in c:\ai\comfyui_windows_portable_sand\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.49.20)
Requirement already satisfied: numpy in c:\ai\comfyui_windows_portable_sand\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: tqdm in c:\ai\comfyui_windows_portable_sand\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (4.67.1)
Requirement already satisfied: opencv-python in c:\ai\comfyui_windows_portable_sand\python_embeded\lib\site-packages (from -r requirements.txt (line 5)) (4.11.0.86)
Requirement already satisfied: matplotlib in c:\ai\comfyui_windows_portable_sand\python_embeded\lib\site-packages (from -r requirements.txt (line 6)) (3.10.0)
Collecting tensorrt_cu12==10.9.0.34 (from tensorrt->-r requirements.txt (line 1))
  Downloading tensorrt_cu12-10.9.0.34.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorrt_cu12_libs==10.9.0.34 (from tensorrt_cu12==10.9.0.34->tensorrt->-r requirements.txt (line 1))
  Downloading tensorrt_cu12_libs-10.9.0.34.tar.gz (704 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 106, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 97, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 386, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 702, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable_sand\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 402, in _call_hook
    raise BackendUnavailable(
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'wheel_stub.buildapi'
```
