### ISSUE TITLE
engine file!

### ISSUE THREAD

**Issue by goodluck821** [yuvraj108c/ComfyUI-Dwpose-Tensorrt#6]
cannot Build tensorrt engines for both of these models by running python export_trt.py!Why?

**Comment by yuvraj108c** [comment]
share the error log /:

**Comment by stylobcn** [comment]
Good morning, I have the same problem and the truth is that I don't have much of an idea either, it gives me this error.

D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dwpose-Tensorrt>D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe export_trt.py
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dwpose-Tensorrt\export_trt.py", line 3, in <module>
    from trt_utilities import Engine
ModuleNotFoundError: No module named 'trt_utilities'

thanks so much

**Comment by stylobcn** [comment]
> share the error log /:

Good morning, I have the same problem and the truth is that I don't have much of an idea either, it gives me this error.

D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dwpose-Tensorrt>D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe export_trt.py
Traceback (most recent call last):
File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dwpose-Tensorrt\export_trt.py", line 3, in
from trt_utilities import Engine
ModuleNotFoundError: No module named 'trt_utilities'

thanks so much
